default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: peter284
  host: localhost
  port: 5432

development:
  <<: *default
  database: diary_app_development

test:
  <<: *default
  database: diary_app_test

production:
  <<: *default
  database: diary_app_production
