# Name of your application. Used to uniquely configure containers.
service: digial_diary

# Name of the container image.
image: diary_app-web/digial_diary

# Deploy to these servers.
servers:
  web:
    - 139.180.171.219

ssh:
  user: root

# (Other sections can remain as defaults or be configured as needed)

